;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Afflictions",NewTagName="Affliction")
+GameplayTagRedirects=(OldTagName="Afflictions.Bleeding",NewTagName="Affliction.Bleeding")
+GameplayTagRedirects=(OldTagName="Affliction.Wounded",NewTagName="Affliction.OpenWound")
+GameplayTagRedirects=(OldTagName="Affliction.Amputated.Arm",NewTagName="Affliction.Arm")
+GameplayTagRedirects=(OldTagName="Affliction.Amputated",NewTagName="Affliction.Arm.Amputated")
+GameplayTagRedirects=(OldTagName="Affliction.Amputated.Leg",NewTagName="Affliction.Leg")
+GameplayTagRedirects=(OldTagName="Affliction.Broken",NewTagName="Affliction.Leg.Broken")
+GameplayTagRedirects=(OldTagName="Affliction.Arm.Amputated",NewTagName="Affliction.Arm.Right.Amputated")
+GameplayTagRedirects=(OldTagName="Affliction.Arm.Broken",NewTagName="Affliction.Arm.Right.Broken")
+GameplayTagRedirects=(OldTagName="Affliction.Arm.Sprained",NewTagName="Affliction.Arm.Right.Sprained")
+GameplayTagRedirects=(OldTagName="Affliction.Leg.Broken",NewTagName="Affliction.Leg.Right.Broken")
+GameplayTagRedirects=(OldTagName="Affliction.Leg.Amputated",NewTagName="Affliction.Leg.Right.Amputated")
+GameplayTagRedirects=(OldTagName="Affliction.Leg.Sprained",NewTagName="Affliction.Leg.Right.Sprained")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Affliction",DevComment="")
+GameplayTagList=(Tag="Affliction.Arm",DevComment="")
+GameplayTagList=(Tag="Affliction.Arm.Left",DevComment="")
+GameplayTagList=(Tag="Affliction.Arm.Left.Amputated",DevComment="")
+GameplayTagList=(Tag="Affliction.Arm.Left.Broken",DevComment="")
+GameplayTagList=(Tag="Affliction.Arm.Left.Sprained",DevComment="")
+GameplayTagList=(Tag="Affliction.Arm.Right.Amputated",DevComment="")
+GameplayTagList=(Tag="Affliction.Arm.Right.Broken",DevComment="")
+GameplayTagList=(Tag="Affliction.Arm.Right.Sprained",DevComment="")
+GameplayTagList=(Tag="Affliction.Bitten",DevComment="")
+GameplayTagList=(Tag="Affliction.Bleeding",DevComment="")
+GameplayTagList=(Tag="Affliction.Burned",DevComment="")
+GameplayTagList=(Tag="Affliction.Cold",DevComment="")
+GameplayTagList=(Tag="Affliction.Dirty",DevComment="")
+GameplayTagList=(Tag="Affliction.Dirty.Other",DevComment="")
+GameplayTagList=(Tag="Affliction.Dirty.Zombie",DevComment="")
+GameplayTagList=(Tag="Affliction.Exposed",DevComment="")
+GameplayTagList=(Tag="Affliction.Freezing",DevComment="")
+GameplayTagList=(Tag="Affliction.Gagged",DevComment="")
+GameplayTagList=(Tag="Affliction.Hot",DevComment="")
+GameplayTagList=(Tag="Affliction.Infected",DevComment="")
+GameplayTagList=(Tag="Affliction.Infected.Other",DevComment="")
+GameplayTagList=(Tag="Affliction.Infected.Zombie",DevComment="")
+GameplayTagList=(Tag="Affliction.Injured",DevComment="")
+GameplayTagList=(Tag="Affliction.Leg",DevComment="")
+GameplayTagList=(Tag="Affliction.Leg.Left",DevComment="")
+GameplayTagList=(Tag="Affliction.Leg.Left.Amputated",DevComment="")
+GameplayTagList=(Tag="Affliction.Leg.Left.Broken",DevComment="")
+GameplayTagList=(Tag="Affliction.Leg.Left.Sprained",DevComment="")
+GameplayTagList=(Tag="Affliction.Leg.Right",DevComment="")
+GameplayTagList=(Tag="Affliction.Leg.Right.Amputated",DevComment="")
+GameplayTagList=(Tag="Affliction.Leg.Right.Broken",DevComment="")
+GameplayTagList=(Tag="Affliction.Leg.Right.Sprained",DevComment="")
+GameplayTagList=(Tag="Affliction.LowHP",DevComment="")
+GameplayTagList=(Tag="Affliction.OnFire",DevComment="")
+GameplayTagList=(Tag="Affliction.OpenWound",DevComment="")
+GameplayTagList=(Tag="Affliction.Sick",DevComment="")
+GameplayTagList=(Tag="Affliction.Snared",DevComment="")
+GameplayTagList=(Tag="Affliction.SteamBurn",DevComment="")
+GameplayTagList=(Tag="Affliction.Stunned",DevComment="")
+GameplayTagList=(Tag="Affliction.Submerged",DevComment="")
+GameplayTagList=(Tag="Affliction.Submerged.Full",DevComment="")
+GameplayTagList=(Tag="Affliction.Submerged.Partial",DevComment="")
+GameplayTagList=(Tag="Affliction.Unconcious",DevComment="")
+GameplayTagList=(Tag="Affliction.Wet",DevComment="")

